#
## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
# override common configurations in common module
servicecomb-config-order: 10

CSE_V1_SC: http://127.0.0.1:30100
CSE_V1_CC: http://127.0.0.1:30113

servicecomb:
  datacenter:
    name: test2
    availableZone: AZ2
    region: region

  service:
    application: demo-java-chassis-cse-v1
    name: provider
    version: 0.0.1
    registry:
      address: ${CSE_V1_SC}
      instance:
        watch: false
  config:
    client:
      serverUri:  ${CSE_V1_CC}
      fileSource: provider.yaml

  monitor:
    client:
      enabled: true
      serverUri: http://127.0.0.1:30109

  handler:
    chain:
      Provider:
        default: bizkeeper-provider

  rest:
    address: 0.0.0.0:9090 # should be same with server.port to use web container
